services:
  - type: web
    name: wintrich-tech-api
    env: dotnet
    rootDir: web-api
    buildCommand: dotnet publish -c Release -o out
    startCommand: dotnet out/NetworkApi.dll
    envVars:
      - key: PORT
        value: 8080
